### ISSUE TITLE
Won't start, JEI might be the problem

### ISSUE THREAD

**Issue by WillNewbie** [EnigmaticaModpacks/Enigmatica2#740]
### Modpack Version

1.79

### Describe your issue.

It goes through the loading process normally until it hits a certain point in loading Just Enough Items. It then freezes, waits for a while, then crashes. I have deleted an restarted the modpack several times and it has yet to load.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Sounds like you haven't allocated enough RAM and/or your PC does not have enough RAM to run the modpack.
https://wiki.enigmatica.net/main/help-desk/guides/allocating-memory
