### ISSUE TITLE
Advancements not Working

### ISSUE THREAD

**Issue by VoidMage236** [EnigmaticaModpacks/Enigmatica2#743]
### Modpack Version

1.1.6

### Describe your issue.

For some reason when I complete certain objectives that are mentioned in the advancement tab such a getting the book for root 3 the advancement will not say complete. Is this a user error or this a bug?

### Have you modified the modpack?

Yes

### User Modifications

I have turned on radiation for Nuclearcraft.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by VoidMage236** [comment]
Never mind sorry for wasting your time. The bug is with the roots mod it self.

**Comment by VoidMage236** [comment]
Also the issue was with an non associated modpack called enigmatica 2 extended that gave me a link to this page for bug help. I am really sorry for wasting your time.

**Comment by NielsPilgaard** [comment]
No worries :)
