### ISSUE TITLE
Wrong PlayerHead issue with enchants gives you a swastika head

### ISSUE THREAD

**Issue by JoeTheLuminary** [EnigmaticaModpacks/Enigmatica2#744]
### Modpack Version

1.79

### Describe your issue.

Beheading enchant(IDK what mod its from) can drop the Withers head upon kill. Withers head is a literal swastika. full red border and white circle around it. maybe disable enchant if possible
![2023-01-07_21 39 09](https://user-images.githubusercontent.com/122193379/211180914-cf9d1bc0-14c3-45f5-b4f9-f195ec0452a1.png)

### Have you modified the modpack?

Yes

### User Modifications

Changed config to enable ExtraUtils chunk loader

### Did the issue happen in singleplayer or on a server?

Server

**Comment by ReiDaTecnologia** [comment]
wtf
Does this issue happens in singleplayer? as it is a server, someone could be messing with it (Unless you play it by yourself)

**Comment by ReiDaTecnologia** [comment]
> wtf Does this issue happens in singleplayer? as it is a server, someone could be messing with it (Unless you play it by yourself)

I just tested and it drops [MHF_Wither](https://pt.namemc.com/profile/MHF_Wither.1)'s Head which is the wither head but somehow and for some reason, the game shows that head instead... weirdest issue i ever saw

**Comment by JoeTheLuminary** [comment]
> wtf I just tested using a Staff of Power enchanted with Cyclic's Beheading enchantment and it drops [MHF_Wither](https://namemc.com/profile/MHF_Wither.1)'s Head which is the wither head but somehow and for some reason, the game shows that head instead... weirdest issue i ever saw

I pay to have the server hosted for me and a couple of friends, im the only one with console access, nothing involving it has been changed. Head name is MHF_Wither and looking it up on nameMC doesnt show that player having this head. I have not changed anything related to heads or enchants. only a couple ExtraUtils things in the config(Enabling some disabled blocks)

**Comment by NielsPilgaard** [comment]
Oh boy, that's a nasty bug. @ReiDaTecnologia did you test in 1.79 as well or 1.86?

**Comment by ReiDaTecnologia** [comment]
> Oh boy, that's a nasty bug. @ReiDaTecnologia did you test in 1.79 as well or 1.86?

I tested with the version provided: Enigmatica 2 1.79

**Comment by JoeTheLuminary** [comment]
I'm not too smart when it comes to this stuff but is there anything I can do to help?

**Comment by NielsPilgaard** [comment]
Testing with the latest version of E2E would be very helpful :)

**Comment by ReiDaTecnologia** [comment]
So i decided to test this in Vanilla 1.12.2 and the latest version (1.19.3) and it affects vanilla as well... Did Mojang got hacked or something? 😱

**Comment by NielsPilgaard** [comment]
Oh, yikes. Perhaps the player just changed his skin? 😄

**Comment by ReiDaTecnologia** [comment]
> Oh, yikes. Perhaps the player just changed his skin? 😄

Nope as you can see [here](https://namemc.com/profile/MHF_Wither.1), the player's head uses the intended head ([Wither Boss Head](https://minecraft.fandom.com/wiki/Wither)) but when you get the head in-game using `/give @p minecraft:skull 1 3 {SkullOwner:"MHF_Wither"}` (1.12.2 and before) or `/give @p minecraft:player_head{SkullOwner:"MHF_Wither"}` (1.13 and after), you get that head instead. Looks like someone did something in background or less likely, it is a bug.
