### ISSUE TITLE
Stuck on loading screen at 0%

### ISSUE THREAD

**Issue by stomp4y** [EnigmaticaModpacks/Enigmatica2#747]
### Modpack Version

1.90e

### Describe your issue.

I launch the modpack, select my savefile but it goes nowhere after that. It says on the loading screen at 0%.

I can press 'ESC' to exit that screen and try to load the game again but as soon as I click my savefile my screen freezes and I'm forced to close the game.

I've already tried allocating more and less RAM; I tried editing my position with a NBT Editor in case I was in a corrupted chunk; Installing JAVA.

I've uploaded two crash logs, one was from the very first time that the issue happened and the other one is a recent one. There's a debug.log too

### Latest Log

https://gist.github.com/stomp4y/fca80bc65f3271c203ee730b23ec68b4

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Asss0mbradO#9290

**Comment by NielsPilgaard** [comment]
Hmm strange 🤔 the logs are fairly clean, but right before the game stops in the debug.log there's a log from RandomPatches. Can you remove that mod and try again please?

Also, I see you're still using Java 8_51, that can cause issues too.

**Comment by stomp4y** [comment]
Tried both, nothing worked :(

**Comment by ReiDaTecnologia** [comment]
Stupid question but after u cllick to load ur save (After u press Esq) and it freezes, did u tried to wait for it to perhaps unfreeze?

**Comment by stomp4y** [comment]
Yes, I waited roughly 1 hour and I managed to enter my save but it was all for nothing, when I got in, the world was all black, I couldn't see my hands or do anything besides opening my inventory. I waited another hour or so then I got bored and left. 

É bom saber que existem mais brasileiros na comunidade de E2E :)

**Comment by NielsPilgaard** [comment]
Could you please provide a debug.log where your game uses more recent java 8? :)

**Comment by stomp4y** [comment]
[debug.log](https://github.com/EnigmaticaModpacks/Enigmatica2/files/12062305/debug.log)

IDK if i'm using the right version, I uninstalled and installed java 3x and at the beggining of the log it "says version 1.8.0_51"

**Comment by NielsPilgaard** [comment]
You need to go into CurseForge Minecraft settings and set the version there :)

**Comment by stomp4y** [comment]
TBH idk what i'm doing wrong. I installed Java directly from the website and selected on curseforge but it's always the same version.

**Comment by stomp4y** [comment]
Well, I tried restoring the latest backup that I had but it didn't work. I was reluctant to restore an older one and lose progress but I did it and now it's working fine. Thank you for your help!!!
