### ISSUE TITLE
Infinite Fresh Water

### ISSUE THREAD

**Issue by fearvector** [EnigmaticaModpacks/Enigmatica2#749]
### Modpack Version

1.90f

### Describe your issue.

Discorvered what i suspect is a Ore Dictonary issue. Pams Harvestcraft Fresh Water is being treated as a bucket, meaning i can make 4 fresh water from 1 bucket then use that Fresh Water to make 32 more. This isnt a major issue till you bring in auto crafters simplifying the process significantly. It may also break intended progression with Mekanism Chemical Infuser, as i can from quite early on make a semi functonal salt setup out of this without progressing to Fluid Crafting Methods, to sudo avoid the need for the Chemical Infuser.

Have Attempted to blacklist this recipe in OreDictInt.cfg but i dont really understand what im doing for this ore if it is directly a Ore Dictonary issue. So if this is not intedened to be fixed, i would still like to know how to disable it for my own private server if possible.

![image](https://github.com/EnigmaticaModpacks/Enigmatica2/assets/36361597/927b4951-f643-41e5-b817-939e1369bb5d)
![image](https://github.com/EnigmaticaModpacks/Enigmatica2/assets/36361597/8619cb9b-8f89-4726-a5cd-4852731b8122)
![image](https://github.com/EnigmaticaModpacks/Enigmatica2/assets/36361597/e45cc34f-a760-4311-a3d1-9665f38f131b)

### Have you modified the modpack?

Yes

### User Modifications

Added Optifine

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

Fear Vector

**Comment by NielsPilgaard** [comment]
Thanks for the report, but this is intended behaviour 👍

**Comment by fearvector** [comment]
Good to know its intended.
But as i feel this breaks some of the gating and difficulty this pack seems to build around and what i have liked for so many years while playing different versions of it (We play Expert btw). I did some research how i could modify this for my self and my friends on my personal server i am running. So i have added the following to Harvestcraft.zs in the scripts folder of the pack.

`# Remove freshwater from itself and allow all water containg items to be used.
recipes.removeShapeless(<harvestcraft:freshwateritem>);
recipes.addShapeless(<harvestcraft:freshwateritem> * 8,[<minecraft:water_bucket> | <liquid:water> * 1000]);`

This leaves my players able to still get 8x Fresh Water from a bucket like before, but also able to use any water containing container like a Jerry Can, Portable tank or Mekanism tanks to off set the lack of access to the Cooking for Block Heads sink.

While also still being able to lean on things ive personally felt this pack was designed around be a awesome middle to end game function, of using machines like the Fluid Crafter or the Sequential Fabricator with fluid crafting augment to automate this latter.

I leave this here, not to undermine your own vision for this pack, but incase anybody else would like to make this change for there own personal servers. While not needing to spend a night and half a day working out how Mods / Craft Tweaker works like me.
