### ISSUE TITLE
multimc

### ISSUE THREAD

**Issue by kleshas** [EnigmaticaModpacks/Enigmatica2#750]
### Modpack Version

1.12

### Describe your issue.

Coming back to minecraft after a couple of years.  Trying to set up an enigmatica 2 instance with multimc with no luck.  Importing the zip gives a "archive does not contain a recognizable modpack type"
Same error with prismlauncher.
Trying to import a cursforge enigamtica 2:  "Job 'Modpack download' failed to process:
https://www.curseforge.com/minecraft/modpacks/enigmatica2"

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Kanzaji** [comment]
This is a n issue with MultiMC not having support for CurseForge for some time now. Use the import feature of MMC from different launcher, 3rd party tool to download the mods or use different Launcher like CF one ^^"

**Comment by kleshas** [comment]
Thanks

**Comment by MommyHeather** [comment]
> Thanks

Just as a tip - prism launcher is a multimc fork which retains the same sort of ui, whilst adding features such as proper curseforge support and better instance management.
