### ISSUE TITLE
Missing fluid input

### ISSUE THREAD

**Issue by Patuik** [EnigmaticaModpacks/Enigmatica2#751]
### Modpack Version

Project Overpoewered RELEASE 3.2 AE2FIX

### Describe your issue.

I made Fusion forge block by block and its not working for some reason. I tried to rebuilt it but still same Status. Anybody have idea for solution?
![obrázek_2024-05-04_100353038](https://github.com/EnigmaticaModpacks/Enigmatica2/assets/94555099/ef01cef2-ec50-4da9-af0d-06fc99d88eeb)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Kanzaji** [comment]
Hey there, thanks for the report. However, this is an issue tracker for Enigmatica 2 modpack, not Project Overpowered 😅

From what I found, the author of that modpack takes bug reports on curse forge private messages 😜

**Comment by Patuik** [comment]
So, what should I do with that?

**Comment by NielsPilgaard** [comment]
You can send him this bug report. We cannot help you unfortunately.
