### ISSUE TITLE
Error Starting Server in Pterodactyl instance

### ISSUE THREAD

**Issue by Sano-WasTaken** [EnigmaticaModpacks/Enigmatica2#752]
### Modpack Version

Latest

### Describe your issue.

i tried many time to create an E2E server on my own server but i always have this:
"About to start server. Force re-install (y/n)?  Ping to Google DNS failed. No internet access?
Ping to L4 failed. No internet access?"
My server have internet access so i don't understand the issue...

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
It most likely means that outbound communication from your server is restricted. 
You can remove the part of the startup script that pings google to fix this 😊
